# Generated by Django 2.0.7 on 2019-03-12 05:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('author_name', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('date_of_submission', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
